---
Gemfile:
  optional:
    ':test':
      - gem: 'toml'
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_types
    - parameter_documentation

.github/workflows/ci.yml:
  with:
    acceptance_runs_on: macarne
